services:
  aico-task-db:
    image: "postgres:18"

    ports:
      - 5433:5432

    environment:
      POSTGRES_USER: aico
      POSTGRES_PASSWORD: aicopassword
      POSTGRES_DB: aico_task_db

    volumes:
      - aico_task_db_data:/var/lib/postgresql

volumes:
  aico_task_db_data:
